# Generated by Django 3.1.7 on 2021-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
